Presentacion/CapaPresentacion/Controllers/OrdenProduccionController.cs
using CapaPresentacionAdmin.Models;
using Datos;
using Microsoft.Ajax.Utilities;
using Negocio.Interfaces;
using Negocio.Modelos;
using Negocio.Repositorio;
using Negocio.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace QCS.Controllers
{
    public class OrdenProduccionController : Controller
    {
       
        private readonly Servicio_OP op_service;
        private IRepoOrdenProduccion _repoOP;
        private IRepoModelo _repoModelo;
        private IRepoColor _repoColor;
        private IRepoLinea _repoLinea;
        private IRepoUsuario _repoUsuario;

        public OrdenProduccionController()
        {
            if (op_service == null)
            {

                op_service= new Servicio_OP();
            }

            if (_repoOP == null)
            {

                _repoOP = new RepoOrdenProduccion();
            }
            if (_repoModelo == null)
            {

                _repoModelo = new RepoModelo();
            }

            if (_repoColor == null)
            {

                _repoColor = new RepoColor();
            }
            if (_repoLinea == null)
            {

                _repoLinea = new RepoLinea();
            }
            if (_repoUsuario == null)
            {

                _repoUsuario = new RepoUsuario();
            }
        }

        // GET: OrdeProduccion
        public ActionResult Index()
        {
            var listaOP = _repoOP.ListarOP();
            foreach (var op in listaOP)
            {
                op.Modelo = _repoModelo.BuscarModelo(op.Sku_modelo);
                op.Color = _repoColor.BuscarColor(op.Codigo_color);
                op.Usuario = _repoUsuario.BuscarUsuario(op.Id_usuario);
            }
            return View(listaOP);
        }


        public ActionResult Create()
        {
            var listaModelos = _repoModelo.ListarModelos();
            var listaLineas = _repoLinea.ObtenerLineasDisponibles();
            


            ViewBag.listamodelos = new SelectList(listaModelos, "SKU", "Denominacion");
            ViewBag.listalineas = new SelectList(listaLineas, "Numero_Linea", "Numero_Linea");

            return View();
        }


        // POST: OrdeProduccion/Create
        [HttpPost]
        public ActionResult Create(VMOrdenProduccion orden)
        {
            if (!ModelState.IsValid)
            {
                return View(orden);
            }

            var usuario = Session["Usuario"] as ModeloUsuario;
            var op = new ModeloOP
            {
                Numero_OP = orden.Numero_OP,
                Sku_modelo = orden.Sku_modelo,
                Codigo_color = orden.Codigo_color,
                Num_linea = orden.Num_linea,
            };

            var resultadoCreacion = op_service.CrearOP(op, usuario.Legajo);

            if (!resultadoCreacion.exito)
            {
                return HandleCreateErrors(orden, resultadoCreacion.mensaje);
            }

            return RedirectToAction("Index");
        }


        public ActionResult ReanudarOP(int numero_op, int legajo)

        {
            var usuario = Session["Usuario"] as ModeloUsuario;
            op_service.ReanudarOP(numero_op, usuario.Legajo);
            return RedirectToAction("Index");

        }

        public ActionResult FinalizarOP(int numero_op)

        {
            op_service.FinalizarOP(numero_op);
            return RedirectToAction("Index");

        }


        public ActionResult GetColordelModelo(int sku_model)
        {
            var colores = _repoModelo.BuscarModelo(sku_model).Colores
                                          .Select(c => new SelectListItem
                                          {
                                              Value = c.Codigo.ToString(),
                                              Text = c.Descripcion
                                          }).ToList();
            return Json(colores, JsonRequestBehavior.AllowGet);
        }

        private ActionResult HandleCreateErrors(VMOrdenProduccion orden, string mensaje)
        {
            ViewBag.Mensaje = mensaje;
            var listaModelos = _repoModelo.ListarModelos();
            var listaLineas = _repoLinea.ObtenerLineasDisponibles();
            ViewBag.listamodelos = new SelectList(listaModelos, "SKU", "Denominacion");
            ViewBag.listalineas = new SelectList(listaLineas, "Numero_Linea", "Numero_Linea");
            return View(orden);
        }




        //// GET: OrdeProduccion/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: OrdeProduccion/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: OrdeProduccion/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: OrdeProduccion/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }


        //}




    }





}
    

Presentacion/CapaPresentacion/Views/OrdenProduccion/Create.cshtml
@model CapaPresentacionAdmin.Models.VMOrdenProduccion

@{
    ViewBag.Title = "Create";
}

<style>
    .btn-green {
        background-color: green;
        color: white;
    }
    .form-group {
        margin-bottom: 20px;
    }



</style>


<h2>Inciar Orden de Produccion</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Numero_OP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero_OP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero_OP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Num_linea, "Linea", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Num_linea, (IEnumerable<SelectListItem>)ViewBag.listalineas, "Seleccione una linea", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Num_linea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sku_modelo, "Modelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sku_modelo, (IEnumerable<SelectListItem>)ViewBag.listamodelos, "Seleccione un modelo", new { @class = "form-control", id = "selectModelo" })
                @Html.HiddenFor(model => model.Sku_modelo, new { id = "model-sku" })
                @Html.ValidationMessageFor(model => model.Sku_modelo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group" >
            @Html.LabelFor(model => model.Codigo_color, "Color", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Codigo_color, Enumerable.Empty<SelectListItem>(), "Seleccione un color", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Codigo_color, "", new { @class = "text-danger" })
            </div>
        </div>

       <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <button type="submit" class="btn btn-green">Crear</button>
    </div>
      </div>
</div>
}

@if (!string.IsNullOrEmpty(ViewBag.Mensaje))
  {
    <div class="alert alert-danger" style="margin-bottom: 10px;">@ViewBag.Mensaje</div>
  }

<div style="margin-bottom: 20px;">
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>


<script>
$(function () {
    $('#selectModelo').change(function () {
        var url = '@Url.Action("GetColordelModelo", "OrdenProduccion")';
        var modeloId = $(this).val();
        $.getJSON(url, { sku_model: modeloId }, function (data) {
            var items = '<option>Seleccione un color</option>';
            $.each(data, function (i, color) {
                items += "<option value='" + color.Value + "'>" + color.Text + "</option>";
            });
            $('#Codigo_color').html(items); // Aquí se usa el id "Codigo_color" que es el mismo que se definió en el dropdownlist.
        })
        .done(function(data) {
            console.log(data); // Aquí se muestra la respuesta del servidor en la consola.
        })
        .fail(function(jqXHR, textStatus, errorThrown) {
            console.log(textStatus + ': ' + errorThrown);
        });
    });
});

</script>

<script>
    $(document).ready(function () {
        $('form').validate();
    });
</script>

Presentacion/CapaPresentacion/Views/OrdenProduccion/Index.cshtml
@model IEnumerable<Negocio.Modelos.ModeloOP>

@{
    ViewBag.Title = "Index";
}

<style>

    .table-style {
        border-collapse: collapse;
        border-spacing: 0;
    }

        .table-style th {
            background-color: #97C2C1;
            border: 1px solid black;
            
        }

        .table-style td {
            border: 1px solid black;
        }

    .btn-pausar {
        background-color: yellow;
        color: black;
         border: 1px solid black;
    }

    .btn-reanudar {
        background-color: green;
        color: white;
        border: 1px solid black;
    }

    .btn-finalizar {
        background-color: red;
        color: white;
        border: 1px solid black;
    }


</style>

<h2>Index</h2>

<p>
    @Html.ActionLink("Iniciar Orden de Produccion", "Create")
</p>
<table class="table table-style">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Numero_OP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_I)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado_OP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Num_linea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Denominacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Usuario.Nombre_Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_jornada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_F)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Numero_OP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_I)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado_OP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Num_linea)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo.Denominacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color.Descripcion)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Usuario.Nombre_Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id_jornada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_F)
        </td>
        <td>
            @Html.ActionLink("Pausar", "Pausar", new { id = item.Numero_OP }, new { @class = "btn-pausar" })
            @Html.ActionLink("Reanudar", "Reanudar", new { id = item.Numero_OP }, new { @class = "btn-reanudar" })
            @Html.ActionLink("Finalizar", "Finalizar", new { id = item.Numero_OP }, new { @class = "btn-finalizar" })


        </td>
    </tr>
}

</table>